# Generated by Django 5.1.2 on 2024-10-26 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_statement_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('money_out', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
            ],
        ),
    ]
