# Generated by Django 5.1.2 on 2024-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorisedTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_statement_uid', models.UUIDField(editable=False)),
                ('category', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money_out', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('money_in', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_statement_uid',
            field=models.UUIDField(editable=False),
        ),
    ]
