# Generated by Django 5.1.2 on 2024-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categorisedtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorisedtransaction',
            name='bank_statement_uid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_statement_uid',
            field=models.UUIDField(),
        ),
    ]
